package com.rhythmphysics.desktop

import com.rhythmphysics.core.audio.AudioAnalysis
import com.rhythmphysics.core.audio.AudioAnalyzer
import com.rhythmphysics.core.audio.WavReader
import com.rhythmphysics.core.audio.WavWriter
import com.rhythmphysics.core.engine.RhythmEngine
import com.rhythmphysics.core.mechanic.MechanicType
import com.rhythmphysics.core.midi.MidiFile
import com.rhythmphysics.core.music.BeatGrid
import com.rhythmphysics.core.preset.PresetManager
import com.rhythmphysics.core.render.AspectRatio
import com.rhythmphysics.core.render.DrawList
import com.rhythmphysics.core.render.RenderSettings
import com.rhythmphysics.core.session.AudioEventSource
import com.rhythmphysics.core.session.MediaType
import com.rhythmphysics.core.session.ReplayManager
import com.rhythmphysics.core.session.RhythmSession
import com.rhythmphysics.core.session.SceneConfig
import com.rhythmphysics.core.session.ViewMode
import com.rhythmphysics.core.synth.MidiRenderer
import com.rhythmphysics.core.synth.Sf2Synth
import com.rhythmphysics.core.synth.SoundFont
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import java.io.File
import kotlin.math.abs
import kotlin.math.ceil
import kotlin.math.sin

/**
 * Regenerates the measurable artifacts (artifacts/sync, perf, replays, test-reports):
 *
 *   desktop gauntlet <artifacts dir> [soundfont.sf2]
 *
 * Everything here runs the shared core engine on the host JVM. Device timing (AudioTrack
 * latency, display presentation, MediaCodec) is not measurable here and is reported as such.
 */
object Gauntlet {
    private val json = Json { prettyPrint = true }
    private fun r(v: Double, d: Int = 3) = Math.round(v * Math.pow(10.0, d.toDouble())) / Math.pow(10.0, d.toDouble())
    private fun write(f: File, e: JsonElement) { f.parentFile.mkdirs(); f.writeText(json.encodeToString(JsonElement.serializer(), e) + "\n"); println("wrote $f") }

    private fun pct(sorted: List<Double>, p: Double) = if (sorted.isEmpty()) 0.0 else sorted[((sorted.size - 1) * p).toInt()]

    fun run(out: File, soundFont: File?) {
        val md = StringBuilder("# Gauntlet report\n\nGenerated by `desktop gauntlet` on the host JVM (${System.getProperty("os.arch")}, Java ${System.getProperty("java.version")}).\n" +
            "Device-only behaviour (AudioTrack latency, display presentation, MediaCodec, thermals) is **not** measured here.\n\n")
        val demo = Scenes.demoSession()
        sync(out, demo, md)
        audio(out, demo.midi!!, soundFont, md)
        determinism(out, demo, md)
        perf(out, demo, md)
        replays(out, demo, md)
        File(out, "test-reports/GAUNTLET.md").apply { parentFile.mkdirs(); writeText(md.toString()) }
        println("wrote ${File(out, "test-reports/GAUNTLET.md")}")
    }

    // ---- sync ---------------------------------------------------------------------------------
    private fun runSync(session: RhythmSession, cfg: SceneConfig): Pair<RhythmEngine, List<Double>> {
        val e = RhythmEngine(session, cfg)
        var t = 0.0
        while (t < session.durationSec) { e.update(t); t += 1.0 / 60 }
        e.update(session.durationSec)
        return e to e.sync.samples().map { it.expectedTimeSec }
    }

    private fun quantization(expected: List<Double>, hz: Int): JsonObject {
        // An exactly-timed contact first appears on the first frame presented at or after it.
        val errs = expected.map { e -> (ceil(e * hz - 1e-9) / hz - e) * 1000 }.sorted()
        return buildJsonObject { put("hz", hz); put("meanMs", r(errs.average().takeIf { !it.isNaN() } ?: 0.0)); put("p95Ms", r(pct(errs, 0.95))); put("maxMs", r(errs.lastOrNull() ?: 0.0)) }
    }

    private fun sync(out: File, demo: RhythmSession, md: StringBuilder) {
        val rows = ArrayList<JsonObject>()
        md.append("## Sync (logical contact time vs musical event time)\n\n")
        md.append("Planned mechanics solve every contact exactly on the fixed 120 Hz step grid, so logical error is 0 by construction; the numbers below *measure* it from the simulation. Frame quantization is what an ideal 60/90/120 Hz display adds.\n\n")
        md.append("| preset | aspect | contacts | mean ms | p95 ms | max ms | degraded | goal | 60 Hz p95 | 120 Hz p95 |\n|---|---|---|---|---|---|---|---|---|---|\n")
        for (p in PresetManager.builtIns) {
            for (aspect in AspectRatio.values()) {
                val cfg = SceneConfig(seed = 1337, aspect = aspect, focus = p.mechanic, presetIds = mapOf(p.mechanic to p.id))
                val (e, expected) = runSync(demo, cfg)
                val st = e.sync.stats()
                val q60 = quantization(expected, 60); val q90 = quantization(expected, 90); val q120 = quantization(expected, 120)
                rows += buildJsonObject {
                    put("preset", p.id); put("mechanic", p.mechanic.name); put("aspect", aspect.label)
                    put("contacts", st.count); put("meanAbsMs", r(st.meanAbsMs, 4)); put("p95AbsMs", r(st.p95AbsMs, 4)); put("maxAbsMs", r(st.maxAbsMs, 4))
                    put("outliersOver30ms", st.outliersOver30ms); put("degraded", st.degraded); put("passesGoal", st.passesPlannedGoal)
                    put("frameQuantization", JsonArray(listOf(q60, q90, q120)))
                }
                md.append("| ${p.id} | ${aspect.label} | ${st.count} | ${"%.3f".format(st.meanAbsMs)} | ${"%.3f".format(st.p95AbsMs)} | ${"%.3f".format(st.maxAbsMs)} | ${st.degraded} | ${if (st.passesPlannedGoal) "pass" else "FAIL"} | ${q60["p95Ms"]} | ${q120["p95Ms"]} |\n")
                e.dispose()
            }
        }
        write(File(out, "sync/sync_matrix_demo_midi.json"), buildJsonObject {
            put("source", "Orbit Lines (original demo MIDI), 112 BPM, ${"%.1f".format(demo.durationSec)} s")
            put("goal", "mean <= 5 ms, p95 <= 15 ms, max <= 30 ms")
            put("note", "Circle presets are free physics: collisions are not planned musical contacts, so they log no planned-contact samples.")
            put("runs", JsonArray(rows))
        })
        md.append("\n")
    }

    // ---- audio analysis + audio-driven sync ---------------------------------------------------------
    private fun analyze(f: File): AudioAnalysis {
        val info = WavReader.readInfo(f)
        val a = AudioAnalyzer(info.sampleRate)
        WavReader.streamMono(f) { b, n -> a.feed(b, n) }
        return a.finish()
    }

    private fun audio(out: File, midi: MidiFile, sfFile: File?, md: StringBuilder) {
        md.append("## Audio analysis\n\n")
        // Click track with known ground truth.
        val sr = 44100; val bpm = 120.0; val secs = 32.0; val offset = 0.25
        val x = FloatArray((secs * sr).toInt())
        val clicks = ArrayList<Double>()
        var k = 0
        while (true) {
            val t = offset + k * 60.0 / bpm; if (t > secs - 0.5) break
            clicks += t
            val amp = if (k % 4 == 0) 0.9f else 0.5f
            val s0 = (t * sr).toInt()
            for (i in 0 until 1200) if (s0 + i < x.size) x[s0 + i] += (amp * sin(2 * Math.PI * 2000 * i / sr) * Math.exp(-i / 180.0)).toFloat()
            k++
        }
        val a = AudioAnalyzer(sr)
        var i = 0
        while (i < x.size) { val n = minOf(4096, x.size - i); a.feed(x.copyOfRange(i, i + n), n); i += n }
        val click = a.finish()
        val onsetErr = clicks.map { c -> click.onsets.minOf { abs(it.timeSec - c) } * 1000 }.sorted()
        val clickJson = buildJsonObject {
            put("bpmTruth", bpm); put("bpmDetected", r(click.bpm, 2)); put("clicks", clicks.size); put("onsetsDetected", click.onsets.size)
            put("onsetErrorMedianMs", r(pct(onsetErr, 0.5), 2)); put("onsetErrorP95Ms", r(pct(onsetErr, 0.95), 2))
        }
        md.append("- Click track (120 BPM, ${clicks.size} clicks): detected %.2f BPM, onset error median %.2f ms, p95 %.2f ms\n".format(click.bpm, pct(onsetErr, 0.5), pct(onsetErr, 0.95)))

        var demoJson: JsonObject? = null
        var audioSync: JsonArray? = null
        if (sfFile != null && sfFile.exists()) {
            val wav = File(System.getProperty("java.io.tmpdir"), "rp_gauntlet_demo.wav")
            if (!wav.exists()) {
                val synth = Sf2Synth(SoundFont.parse(sfFile.readBytes()), 44100)
                WavWriter(wav, 44100, 2).use { w -> MidiRenderer.render(midi, synth) { l, rr, n -> w.write(l, rr, n) } }
            }
            val an = analyze(wav)
            val grid = BeatGrid.fromMidi(midi)
            val truth = grid.beatTimes.filter { it > 0.3 && it < midi.durationSec - 1 }
            val beatsMatched = truth.count { t -> an.beatTimes.any { abs(it - t) < 0.035 } }
            val bars = grid.beatTimes.filterIndexed { j, _ -> grid.downbeat[j] }.filter { it > 0.3 && it < midi.durationSec - 1 }
            val dbMatched = an.downbeatTimes.count { d -> bars.any { abs(it - d) < 0.035 } }
            val noteOnsets = midi.notes.map { it.startSec }.distinct().sorted()
            val precise = an.onsets.count { o -> noteOnsets.any { abs(it - o.timeSec) < 0.025 } }
            demoJson = buildJsonObject {
                put("source", "Orbit Lines demo rendered with GeneralUser GS (real mixed audio, analysed without the MIDI)")
                put("bpmTruth", 112.0); put("bpmDetected", r(an.bpm, 2))
                put("beatsMatched", beatsMatched); put("beatsTruth", truth.size)
                put("downbeatsOnBarLines", dbMatched); put("downbeatsDetected", an.downbeatTimes.size)
                put("onsetPrecision", r(precise.toDouble() / an.onsets.size.coerceAtLeast(1), 3)); put("onsets", an.onsets.size)
                put("sections", buildJsonArray { an.sections.forEach { add(JsonPrimitive(r(it, 2))) } })
                put("keyPitchClass", an.keyPitchClass ?: -1)
            }
            md.append("- Demo song rendered to audio and analysed blind: %.2f BPM (truth 112), beats %d/%d, downbeats on bar lines %d/%d, onset precision %.0f%%, key pc %s\n"
                .format(an.bpm, beatsMatched, truth.size, dbMatched, an.downbeatTimes.size, 100.0 * precise / an.onsets.size.coerceAtLeast(1), an.keyPitchClass))
            // Audio-driven planned mechanics.
            val session = RhythmSession("audio-demo", "file://demo.wav", "audio-demo-fp", MediaType.AUDIO, "Orbit Lines (audio)", WavReader.readInfo(wav).durationSec, AudioEventSource(an), analysis = an)
            val rows = ArrayList<JsonObject>()
            md.append("\n| audio-driven preset | contacts | mean ms | p95 ms | max ms | goal |\n|---|---|---|---|---|---|\n")
            for (type in MechanicType.values()) {
                val p = PresetManager.defaultFor(type)
                val (e, _) = runSync(session, SceneConfig(seed = 7, focus = type, presetIds = mapOf(type to p.id)))
                val st = e.sync.stats()
                rows += buildJsonObject { put("preset", p.id); put("contacts", st.count); put("meanAbsMs", r(st.meanAbsMs, 4)); put("p95AbsMs", r(st.p95AbsMs, 4)); put("maxAbsMs", r(st.maxAbsMs, 4)); put("passesGoal", st.passesPlannedGoal) }
                md.append("| ${p.id} | ${st.count} | ${"%.3f".format(st.meanAbsMs)} | ${"%.3f".format(st.p95AbsMs)} | ${"%.3f".format(st.maxAbsMs)} | ${if (st.passesPlannedGoal) "pass" else "FAIL"} |\n")
                e.dispose()
            }
            audioSync = JsonArray(rows)
        } else md.append("- (SoundFont not supplied: demo audio analysis skipped)\n")
        write(File(out, "test-reports/audio_analysis.json"), buildJsonObject {
            put("analyzerVersion", AudioAnalyzer.VERSION)
            put("clickTrack", clickJson)
            demoJson?.let { put("demoAudio", it) }
        })
        audioSync?.let { write(File(out, "sync/sync_audio_driven.json"), buildJsonObject { put("runs", it) }) }
        md.append("\n")
    }

    // ---- determinism ----------------------------------------------------------------------------------
    private fun determinism(out: File, demo: RhythmSession, md: StringBuilder) {
        md.append("## Determinism (state hash at t = 60 s)\n\n| scene | 60 Hz | 90 Hz | 120 Hz | 144 Hz | seek | all equal |\n|---|---|---|---|---|---|---|\n")
        val scenes = MechanicType.values().map { it.label to SceneConfig(seed = 99, focus = it) } + listOf(
            "Journey" to SceneConfig(seed = 99, viewMode = ViewMode.JOURNEY),
            "Duet" to SceneConfig(seed = 99, viewMode = ViewMode.DUET),
            "Quad" to SceneConfig(seed = 99, viewMode = ViewMode.QUAD, aspect = AspectRatio.SQUARE_1_1),
        )
        val rows = ArrayList<JsonObject>()
        for ((name, cfg) in scenes) {
            val hashes = listOf(60, 90, 120, 144).map { hz ->
                val e = RhythmEngine(demo, cfg); var t = 0.0
                while (t < 60.0) { e.update(t); t += 1.0 / hz }
                e.update(60.0); e.stateHash().also { e.dispose() }
            }
            val seek = RhythmEngine(demo, cfg).let { e -> e.seek(60.0); e.stateHash().also { e.dispose() } }
            val all = (hashes + seek).toSet().size == 1
            rows += buildJsonObject { put("scene", name); put("hashes", buildJsonArray { (hashes + seek).forEach { add(JsonPrimitive(it.take(16))) } }); put("allEqual", all) }
            md.append("| $name | ${hashes.joinToString(" | ") { it.take(8) }} | ${seek.take(8)} | ${if (all) "yes" else "NO"} |\n")
        }
        write(File(out, "test-reports/determinism.json"), buildJsonObject { put("timeSec", 60.0); put("scenes", JsonArray(rows)) })
        md.append("\n")
    }

    // ---- perf (host) -----------------------------------------------------------------------------------
    private fun perf(out: File, demo: RhythmSession, md: StringBuilder) {
        md.append("## Host performance (JVM, not a device)\n\n| scene | sim µs/step | DrawList ms/frame (avg / p95) | draw cmds (avg / max) | Java2D raster ms @540×960 |\n|---|---|---|---|---|\n")
        val scenes = PresetManager.builtIns.map { it.id to SceneConfig(seed = 1337, focus = it.mechanic, presetIds = mapOf(it.mechanic to it.id)) } +
            listOf("journey" to SceneConfig(seed = 1337, viewMode = ViewMode.JOURNEY), "quad" to SceneConfig(seed = 1337, viewMode = ViewMode.QUAD))
        val rows = ArrayList<JsonObject>()
        val rs = RenderSettings()
        for ((name, cfg) in scenes) {
            // Simulation only.
            val sim = RhythmEngine(demo, cfg)
            val t0 = System.nanoTime(); sim.update(60.0) // seek path = pure stepping
            val steps = sim.stepIndex.coerceAtLeast(1)
            val usPerStep = (System.nanoTime() - t0) / 1e3 / steps
            sim.dispose()
            // Frames.
            val e = RhythmEngine(demo, cfg)
            val dl = DrawList()
            val buildMs = ArrayList<Double>(); val cmds = ArrayList<Int>(); val rasterMs = ArrayList<Double>()
            var t = 0.0; var frame = 0
            while (t < 40.0) {
                e.update(t)
                val b0 = System.nanoTime(); e.render(dl, rs); val b1 = System.nanoTime()
                if (t > 2.0) { buildMs += (b1 - b0) / 1e6; cmds += dl.commandCount }
                if (frame % 20 == 0 && t > 2.0) {
                    val r0 = System.nanoTime(); Java2DRenderer(540, 960).render(dl); rasterMs += (System.nanoTime() - r0) / 1e6
                }
                t += 1.0 / 60; frame++
            }
            e.dispose()
            val bs = buildMs.sorted()
            rows += buildJsonObject {
                put("scene", name); put("simMicrosPerStep", r(usPerStep, 2)); put("drawListMsAvg", r(bs.average(), 3)); put("drawListMsP95", r(pct(bs, 0.95), 3))
                put("drawCommandsAvg", r(cmds.average(), 1)); put("drawCommandsMax", cmds.maxOrNull() ?: 0); put("java2dRasterMsAvg", r(rasterMs.average(), 2))
            }
            md.append("| $name | ${"%.1f".format(usPerStep)} | ${"%.3f / %.3f".format(bs.average(), pct(bs, 0.95))} | ${"%.0f / %d".format(cmds.average(), cmds.maxOrNull() ?: 0)} | ${"%.1f".format(rasterMs.average())} |\n")
        }
        write(File(out, "perf/host_perf.json"), buildJsonObject {
            put("host", "${System.getProperty("os.name")} ${System.getProperty("os.arch")}, ${Runtime.getRuntime().availableProcessors()} cpus, Java ${System.getProperty("java.version")}")
            put("note", "Host JVM numbers; Android frame times depend on the device GPU/CPU and are not measured here.")
            put("scenes", JsonArray(rows))
        })
        md.append("\n")
    }

    // ---- replays -----------------------------------------------------------------------------------------
    private fun replays(out: File, demo: RhythmSession, md: StringBuilder) {
        md.append("## Replays (export → import → verify)\n\n| replay | verify at | hash match |\n|---|---|---|\n")
        val dir = File(out, "replays"); dir.mkdirs()
        val cases = listOf(
            "square_classic" to (demo to SceneConfig(seed = 1337, focus = MechanicType.SQUARE, presetIds = mapOf(MechanicType.SQUARE to "square.classic"))),
            "circle_chaos" to (demo to SceneConfig(seed = 42, focus = MechanicType.CIRCLE, presetIds = mapOf(MechanicType.CIRCLE to "circle.chaos"))),
            "arch_bounce_curve_16x9" to (demo to SceneConfig(seed = 5, aspect = AspectRatio.LANDSCAPE_16_9, focus = MechanicType.ARCH, presetIds = mapOf(MechanicType.ARCH to "arch.bounce_curve"))),
            "platform_music_ball" to (demo to SceneConfig(seed = 9, focus = MechanicType.PLATFORM, presetIds = mapOf(MechanicType.PLATFORM to "platform.music_ball"))),
            "journey_auto" to (demo to SceneConfig(seed = 3, viewMode = ViewMode.JOURNEY)),
            "sandbox_taps" to (RhythmSession.sandbox(60.0) to SceneConfig(seed = 11, focus = MechanicType.CIRCLE, presetIds = mapOf(MechanicType.CIRCLE to "circle.sandbox"))),
        )
        val rows = ArrayList<JsonObject>()
        for ((name, pair) in cases) {
            val (session, cfg) = pair
            val e = RhythmEngine(session, cfg)
            var t = 0.0; var tap = 0
            val verifyAt = if (session.mediaType == MediaType.NONE) 12.0 else 45.0
            while (t < verifyAt) {
                e.update(t)
                if (session.mediaType == MediaType.NONE && tap < 6 && t >= 1.0 + tap * 1.5) { e.input("tap", 400f + tap * 60f, 800f + (tap % 3) * 120f); tap++ }
                t += 1.0 / 60
            }
            e.update(verifyAt)
            val text = ReplayManager.export(ReplayManager.create(e, inputs = e.inputLog.toList(), verifyAt = verifyAt))
            File(dir, "$name.replay.json").writeText(text)
            val back = ReplayManager.import(text)
            val re = ReplayManager.engineFor(back, session); re.loadInputs(back.sandboxInputs); re.seek(verifyAt)
            val ok = re.stateHash() == back.verifyHash && back.verifyHash == e.stateHash()
            rows += buildJsonObject { put("replay", "$name.replay.json"); put("verifyAtSec", verifyAt); put("inputs", back.sandboxInputs.size); put("hashMatch", ok) }
            md.append("| $name | ${verifyAt}s | ${if (ok) "yes" else "NO"} |\n")
            e.dispose(); re.dispose()
        }
        write(File(dir, "verification.json"), buildJsonObject { put("replays", JsonArray(rows)) })
        md.append("\n")
    }
}
